version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build:
    docker:
      - image: cimg/node:20.9
    steps:
      - checkout
      - node/install
      - run:
          name: "Build Project"
          command: "npm install && npm run build"

workflows:
  build-and-test:
    jobs:
      - say-hello
      - build:
          requires:
            - say-hello
